name: Helm lint
on:
  pull_request:
    paths:
      - 'kubernetes/**'
      - '.tool-versions'
  push:
    branches:
      - master
    paths:
      - 'kubernetes/**'
      - '.tool-versions'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: '3.10'

      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2

      - name: Install asdf tools
        run: ./asdf-setup.sh

      - name: Lint
        run: >
          helm lint kubernetes/*/*
