name: Terraform lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tool-versions'
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.tool-versions'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.10'

      - name: Install asdf
        uses: asdf-vm/actions/setup@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0

      - name: Install asdf tools
        run: ./asdf-setup.sh

      - name: Lint
        working-directory: ./terraform
        run: >
          terraform fmt --recursive --check --list=true --diff
